name = input("enter your name: ")
length=len(name)
print(length)
space=name.find("S")
print(space)
space2=name.rfind("i")
print(space2)
bname=name.upper()
print(bname)
bname=name.lower()
print(bname)
boool=name.isdigit()
print(boool)
boool=name.isalpha()
print(boool)
cool="980"
res=cool.isdigit()
print(res)
phone_number= "+91-00-123-00-123"
count=phone_number.count("-")
print(count)
phone_number=phone_number.replace("-","")
print(phone_number)